[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log

[program:xvfb]
command=Xvfb :1 -screen 0 %(ENV_DISPLAY_WIDTH)sx%(ENV_DISPLAY_HEIGHT)sx24 -ac +extension GLX +render -noreset
autorestart=true
priority=10

[program:fluxbox]
command=fluxbox
environment=DISPLAY=":1"
autorestart=true
priority=20

[program:x11vnc]
command=x11vnc -display :1 -forever -nopw -shared -rfbport 5900 -quiet
autorestart=true
priority=30

[program:novnc]
command=websockify --web=/usr/share/novnc 6080 localhost:5900
autorestart=true
priority=40
